### ISSUE TITLE
go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer Fails

### ISSUE THREAD

**Issue by nithin-kumar** [DataDog/dd-trace-go#1227]
`[builder  8/11] RUN go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer:   
                                                                                                                                                                              
#14 153.2 # gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
                                                                                                                                                                                                
#14 153.2 /go/src/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:294:33: cannot use msg (type *sketchpb.DDSketch) as type protoreflect.ProtoMessage in argument to "google.golang.org/protobuf/proto".Marshal:                                       
#14 153.2       *sketchpb.DDSketch does not implement protoreflect.ProtoMessage (missing ProtoReflect method)                                                                                                                                                 
#14 153.2 /go/src/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:299:34: cannot use msg (type *sketchpb.DDSketch) as type protoreflect.ProtoMessage in argument to "google.golang.org/protobuf/proto".Marshal:
#14 153.2 	*sketchpb.DDSketch does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
executor failed running [/bin/sh -c go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer]: exit code: 2`

Golang Image : `golang:1.15-alpine`

**Comment by felixge** [comment]
Thanks for submitting this issue.  I'm able to reproduce it like this:

```
$ docker run -it --rm golang:1.15-alpine
$ apk add git
$ go get gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
# gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
src/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:294:33: cannot use msg (type *sketchpb.DDSketch) as type protoreflect.ProtoMessage in argument to "google.golang.org/protobuf/proto".Marshal:
	*sketchpb.DDSketch does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
src/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer/stats.go:299:34: cannot use msg (type *sketchpb.DDSketch) as type protoreflect.ProtoMessage in argument to "google.golang.org/protobuf/proto".Marshal:
	*sketchpb.DDSketch does not implement protoreflect.ProtoMessage (missing ProtoReflect method)
```

Additionally I checked:

- `golang:1.15`: Same issue.
- `golang:1.16-alpine`: No issue.
- go1.15 on macOS: No issue.

So this seems to be specific to go1.15 on linux.

@knusbaum assigning this to you for taking a closer look since you're on escalation rotation this week.

**Comment by gbooth27** [comment]
I am also seeing this issue with `go 1.18` on a mac after upgrading from `go 1.14`

**Comment by gbbr** [comment]
I suspect this was caused by https://github.com/DataDog/dd-trace-go/pull/1188

**Comment by nsrip-dd** [comment]
I think this is a [GOPATH mode vs module-aware mode](https://go.dev/ref/mod#mod-commands) issue. In GOPATH mode (the default for `golang:1.15`) running `go get` downloads the latest version of this library and of all of its dependencies directly from version control, ignoring all of the version information in the `go.mod` file. The `github.com/DataDog/sketches-go` package [recently regenerated their protobuf bindings](https://github.com/DataDog/sketches-go/pull/64) (leading to the error mentioned in this issue. This could be a breaking change in the future and there's already a [PR](https://github.com/DataDog/sketches-go/pull/67) to fix it). But you won't see this error running in module-aware mode since the correct version of `sketches-go` is used rather than the latest commit.

**Comment by nsrip-dd** [comment]
The previously mentioned PR has been merged and this works now.

**Comment by nithin-kumar** [comment]
Thanks @felixge @gbbr @gbooth27 @nsrip-dd for the quick resolution
